name: AIS Collection

on:
  workflow_dispatch:   
  push:
    branches: [main]        # redémarre si on push

jobs:
  collect:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: python ais_stream.py
        env:
          AISSTREAM_API_KEY : ${{ secrets.AISSTREAM_API_KEY }}
          SF_USER           : ${{ secrets.SF_USER }}
          SF_PASSWORD       : ${{ secrets.SF_PASSWORD }}
          SF_ACCOUNT        : ${{ secrets.SF_ACCOUNT }}
          SF_WAREHOUSE      : ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE       : ${{ secrets.SF_DATABASE }}
          SF_SCHEMA         : ${{ secrets.SF_SCHEMA }}
