name: AIS Collection

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  collect:
    runs-on: self-hosted
    environment: snowflake_config

    steps:
      - uses: actions/checkout@v4

      - name: Run AIS stream
        run: run: C:\Users\admin\AppData\Roaming\uv\python\cpython-3.14.4-windows-x86_64-none\python.exe ais_stream.py
        env:
          AISSTREAM_API_KEY : ${{ secrets.AISSTREAM_API_KEY }}
          SF_USER           : ${{ secrets.SF_USER }}
          SF_PASSWORD       : ${{ secrets.SF_PASSWORD }}
          SF_ACCOUNT        : ${{ secrets.SF_ACCOUNT }}
          SF_WAREHOUSE      : ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE       : ${{ secrets.SF_DATABASE }}
          SF_SCHEMA         : ${{ secrets.SF_SCHEMA }}
